function getCodeTemplate() {
	
	var strVar="";
	strVar += "<div id=\"intro\" class=\"col-md-12\">";
	strVar += "      <div class=\"col-md-6\">";
	strVar += "        <div class=\"panel panel-default\">";
	strVar += "          <div class=\"panel-heading\"><h3 id=\"titulo\"><\/h3><\/div>";
	strVar += "          <div id=\"descripcion\" class=\"panel-body\">";
	strVar += "         <\/div>";
	strVar += "         <\/div>";
	strVar += "           ";
	strVar += "        <button type=\"button\" class=\"btn btn-default\" onClick=\"startApp();\">Comenzar gymcana<\/button>";
	strVar += "      <\/div> ";
	strVar += "    <\/div>";
	strVar += "";
	strVar += "    <div id=\"gymcana\" class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "    <div class=\"col-md-8 col-xs-9 col-sm-9\">";
	strVar += "      <div class=\"row\">";
	strVar += "        <div class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "          <div id=\"mainContainer1\" class=\"morfoObject\">";
	strVar += "            ";
	strVar += "          <\/div>";
	strVar += "          <div id=\"mainContainer2\" class=\"morfoObject\">";
	strVar += "            ";
	strVar += "          <\/div>";
	strVar += "          <div id=\"mainContainer3\" class=\"morfoObject\">";
	strVar += "            ";
	strVar += "          <\/div>";
	strVar += "        <\/div>";
	strVar += "        <div id=\"rojoAnswerContainer\" class=\"col-md-6 col-xs-12 col-sm-6 morfoAnswer\">";
	strVar += "          <\/br>";
	strVar += "          <div class=\"form-group\">";
	strVar += "            <div class=\"input-group\">";
	strVar += "            <input id=\"respuestaRojo\" type=\"text\" class=\"form-control\" placeholder=\"Rojo\" \/>";
	strVar += "            <span class=\"input-group-addon\">";
	strVar += "              <button type=\"button\" id=\"btn-rojo\" class=\"btn btn-default btn-xs\" onClick=\"revisarRespuestaRojo();\"><span class=\"glyphicon glyphicon-hand-down\" aria-hidden=\"true\"><\/span><\/button>";
	strVar += "            <\/span>";
	strVar += "            <\/div>";
	strVar += "            <\/br>";
	strVar += "            <input type=\"text\" id=\"lbl-rojo\" class=\"form-control\" value=\"\" disabled\/>";
	strVar += "          <\/div>";
	strVar += "        <\/div>";
	strVar += "        <div id=\"blancoAnswerContainer\" class=\"col-md-6 col-xs-12 col-sm-6 morfoAnswer\">";
	strVar += "          <\/br>";
	strVar += "          <div class=\"form-group\">";
	strVar += "            <div class=\"input-group\">";
	strVar += "            <input id=\"respuestaBlanco\" type=\"text\" class=\"form-control\" placeholder=\"Blanco\" \/>";
	strVar += "            <span class=\"input-group-addon\">";
	strVar += "              <button type=\"button\" id=\"btn-blanco\" class=\"btn btn-default btn-xs\" onClick=\"revisarRespuestaBlanco();\"><span class=\"glyphicon glyphicon-hand-down\" aria-hidden=\"true\"><\/span><\/button>";
	strVar += "            <\/span>";
	strVar += "            <\/div>";
	strVar += "            <\/br>";
	strVar += "            <input type=\"text\" id=\"lbl-blanco\" class=\"form-control\" value=\"\" disabled\/>";
	strVar += "            ";
	strVar += "          <\/div>";
	strVar += "        <\/div>";
	strVar += "      <\/div>";
	strVar += "	<\/div>";
	strVar += "    <div class=\"col-md-4 col-xs-3 col-sm-3\">";
	strVar += "      <div class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "      	<div class=\"input-group\">";
	strVar += "        	<div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-flag\"><\/span><\/div>";
	strVar += "        	<input type=\"text\" id=\"estacionId\" class=\"form-control\" value=\"1\" size=\"2\" disabled\/>";
	strVar += "        	<div class=\"input-group-addon\">\/<\/div>";
	strVar += "        	<input type=\"text\" id=\"estacionMaxId\" class=\"form-control\" value=\"\" size=\"2\" disabled\/>";
	strVar += "      	<\/div>";
	strVar += "      <\/div>";
	strVar += "      <div class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "        <\/br>";
	strVar += "        <div class=\"input-group\">";
	strVar += "        	<div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-ok\"><\/span><\/div> ";
	strVar += "        	<input type=\"text\" id=\"buenasId\" class=\"form-control\" value=\"0\" size=\"2\" disabled\/><\/br>";
	strVar += "        <\/div>";
	strVar += "        <div class=\"input-group\">";
	strVar += "        	<div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-remove\"><\/span><\/div> ";
	strVar += "        	<input type=\"text\" id=\"malasId\" class=\"form-control\" value=\"0\" size=\"2\" disabled\/>";
	strVar += "        <\/div>";
	strVar += "      <\/div>  ";
	strVar += "      <div class=\"col-md-12 col-xs-12 col-sm-12 estacionNav\">";
	strVar += "        <\/br>";
	strVar += "        <div class=\"btn-group btn-group-vertical\" role=\"group\">";
	strVar += "          <button type=\"button\" id=\"btn-nav-1\" class=\"btn-nav btn btn-default btn-lg\" onClick=\"showContainer(1);\">1<\/button>";
	strVar += "          <button type=\"button\" id=\"btn-nav-2\" class=\"btn-nav btn btn-default btn-lg\" onClick=\"showContainer(2);\">2<\/button>";
	strVar += "          <button type=\"button\" id=\"btn-nav-3\" class=\"btn-nav btn btn-default btn-lg\" onClick=\"showContainer(3);\">3<\/button>";
	strVar += "        <\/div>";
	strVar += "      <\/div>  ";
	strVar += "      <\/hr>";
	strVar += "      <div class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "        <\/br>";
	strVar += "          <button type=\"button\" id=\"btn-sgnt-estacion\" class=\"btn btn-default btn-lg\" onClick=\"nextEstacion();\"><span class=\"glyphicon glyphicon-chevron-right\"><\/span><\/button>";
	strVar += "      <\/div>";
	strVar += "      <div class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "        <\/br>";
	strVar += "        <div class=\"input-group\">";
	strVar += "        	<div class=\"input-group-addon\"><span class=\"glyphicon glyphicon-time\"><\/span><\/div> ";
	strVar += "        	<input type=\"text\" id=\"timer\" class=\"form-control\" value=\"60\" size=\"2\" disabled\/>";
	strVar += "        <\/div>";
	strVar += "          ";
	strVar += "      <\/div> ";
	strVar += "      <div class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "        <\/br>";
	strVar += "        <\/br>";
	strVar += "        <div class=\"form-group form-group-lg\">";
	strVar += "          <button type=\"button\" id=\"btn-repetir\" class=\"btn btn-danger\" onClick=\"reiniciar();\"><span class=\"glyphicon glyphicon-repeat\"><\/span><\/button>";
	strVar += "        <\/div>  ";
	strVar += "      <\/div>  ";
	strVar += "";
	strVar += "    <\/div>";
	strVar += "";
	strVar += "    <\/div>";


	strVar = strVar.replace(/(?:\r\n|\r|\n)/g, '<br />');
	//strVar = strVar.replace(/</g, '&lt;');
	//strVar = strVar.replace(/>/g, '&gt;');
	
	return strVar;
}
