function getCodeTemplate() {
	
	var strVar="";
	strVar += "<style>.input-group .form-control {height : inherit;} <\/style>";
	strVar += "    <div id=\"intro\" class=\"col-md-12\">";
	strVar += "      <div class=\"col-md-6\">";
	strVar += "        <h2 id=\"titulo\"><\/h2>";
	strVar += "        <pre id=\"descripcion\"><\/pre>";
	strVar += "        <br \/>";
	strVar += "        <button type=\"button\" class=\"btn btn-default\" onClick=\"startApp();\">Comenzar gymcana<\/button>";
	strVar += "      <\/div> ";
	strVar += "    <\/div>";
	strVar += "";
	strVar += "    <div id=\"gymcana\" class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "    <div class=\"col-md-8 col-xs-9 col-sm-9\">";
	strVar += "      <div class=\"row\">";
	strVar += "        <div class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "          <div id=\"mainContainer1\" class=\"morfoObject\">";
	strVar += "            ";
	strVar += "          <\/div>";
	strVar += "          <div id=\"mainContainer2\" class=\"morfoObject\">";
	strVar += "            ";
	strVar += "          <\/div>";
	strVar += "          <div id=\"mainContainer3\" class=\"morfoObject\">";
	strVar += "            ";
	strVar += "          <\/div>";
	strVar += "        <\/div>";
	strVar += "        <div id=\"rojoAnswerContainer\" class=\"col-md-6 col-xs-6 col-sm-6 morfoAnswer\">";
	strVar += "          <\/br>";
	strVar += "          <div class=\"form-group\">";
	strVar += "            <div class=\"input-group\">";
	strVar += "            <input id=\"respuestaRojo\" type=\"text\" class=\"form-control\" placeholder=\"Rojo\" \/>";
	strVar += "            <span class=\"input-group-addon\">";
	strVar += "              <button type=\"button\" id=\"btn-rojo\" class=\"btn btn-default\" onClick=\"revisarRespuestaRojo();\"><\/button>";
	strVar += "            <\/span>";
	strVar += "            <\/div>";
	strVar += "            <\/br>";
	strVar += "            <input type=\"text\" id=\"lbl-rojo\" class=\"form-control\" value=\"\" disabled\/>";
	strVar += "          <\/div>";
	strVar += "        <\/div>";
	strVar += "        <div id=\"blancoAnswerContainer\" class=\"col-md-6 col-xs-6 col-sm-6 morfoAnswer\">";
	strVar += "          <\/br>";
	strVar += "          <div class=\"form-group\">";
	strVar += "            <div class=\"input-group\">";
	strVar += "            <input id=\"respuestaBlanco\" type=\"text\" class=\"form-control\" placeholder=\"Blanco\" \/>";
	strVar += "            <span class=\"input-group-addon\">";
	strVar += "              <button type=\"button\" id=\"btn-blanco\" class=\"btn btn-default\" onClick=\"revisarRespuestaBlanco();\"><\/button>";
	strVar += "              <\/span>";
	strVar += "            <\/div>";
	strVar += "            <\/br>";
	strVar += "            <input type=\"text\" id=\"lbl-blanco\" class=\"form-control\" value=\"\" disabled\/>";
	strVar += "            ";
	strVar += "          <\/div>";
	strVar += "        <\/div>";
	strVar += "      <\/div>";
	strVar += "	<\/div>";
	strVar += "    <div class=\"col-md-4 col-xs-3 col-sm-3\">";
	strVar += "      <div class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "        <label>Estaci&oacute;n:<\/label> <input type=\"text\" id=\"estacionId\" value=\"1\" size=\"2\" disabled\/>\/<input type=\"text\" id=\"estacionMaxId\" value=\"\" size=\"2\" disabled\/>";
	strVar += "      <\/div>";
	strVar += "      <div class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "        <\/br>";
	strVar += "        <label>Buenas:<\/label> <input type=\"text\" id=\"buenasId\" value=\"0\" size=\"2\" disabled\/><\/br>";
	strVar += "        <label>Malas:<\/label> <input type=\"text\" id=\"malasId\" value=\"0\" size=\"2\" disabled\/>";
	strVar += "      <\/div>  ";
	strVar += "      <div class=\"col-md-12 col-xs-12 col-sm-12 estacionNav\">";
	strVar += "        <\/br>";
	strVar += "        <div class=\"btn-group btn-group-vertical\" role=\"group\">";
	strVar += "          <button type=\"button\" id=\"btn-nav-1\" class=\"btn-nav btn btn-default btn-lg\" onClick=\"showContainer(1);\">1<\/button>";
	strVar += "          <button type=\"button\" id=\"btn-nav-2\" class=\"btn-nav btn btn-default btn-lg\" onClick=\"showContainer(2);\">2<\/button>";
	strVar += "          <button type=\"button\" id=\"btn-nav-3\" class=\"btn-nav btn btn-default btn-lg\" onClick=\"showContainer(3);\">3<\/button>";
	strVar += "        <\/div>";
	strVar += "      <\/div>  ";
	strVar += "      <\/hr>";
	strVar += "      <div class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "        <\/br>";
	strVar += "          <button type=\"button\" id=\"btn-sgnt-estacion\" class=\"btn btn-default btn-lg\" onClick=\"nextEstacion();\">Siguiente estaci&oacute;n<\/button>";
	strVar += "      <\/div>";
	strVar += "      <div class=\"col-md-4 col-xs-4 col-sm-4\">";
	strVar += "        <\/br>";
	strVar += "        <div class=\"form-group form-group-lg\">";
	strVar += "          <input type=\"text\" id=\"timer\" class=\"form-control\" value=\"60\" size=\"2\" disabled\/>";
	strVar += "        <\/div>  ";
	strVar += "      <\/div> ";
	strVar += "      <div class=\"col-md-12 col-xs-12 col-sm-12\">";
	strVar += "        <\/br>";
	strVar += "        <\/br>";
	strVar += "        <div class=\"form-group form-group-lg\">";
	strVar += "          <button type=\"button\" id=\"btn-repetir\" class=\"btn btn-danger\" onClick=\"reiniciar();\">Repetir Gymkana<\/button>";
	strVar += "        <\/div>  ";
	strVar += "      <\/div>  ";
	strVar += "";
	strVar += "    <\/div>";
	strVar += "";
	strVar += "    <\/div>";
	strVar += "";

	strVar = strVar.replace(/(?:\r\n|\r|\n)/g, '<br />');
	//strVar = strVar.replace(/</g, '&lt;');
	//strVar = strVar.replace(/>/g, '&gt;');
	
	return strVar;
}
